import { StyleSheet } from 'react-native';
import { Colors, Spacing, BorderRadius, FontSizes, FontWeights } from './theme';

const cardShadow = {
  shadowColor: '#000',
  shadowOpacity: 0.06,
  shadowRadius: 10,
  shadowOffset: { width: 0, height: 3 },
  elevation: 2,
};

export const dashboardStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.neutral[50],
  },
  headerGradient: {
    paddingHorizontal: Spacing.lg,
    paddingTop: Spacing.sm,
    paddingBottom: 64,
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
  },
  headerTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: Spacing.md,
  },
  headerWelcome: {
    fontSize: FontSizes.sm,
    fontWeight: FontWeights.semibold,
    color: '#dcfce7',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  headerName: {
    fontSize: FontSizes['3xl'],
    fontWeight: FontWeights.bold,
    color: Colors.neutral[0],
    marginTop: Spacing.sm,
  },
  notificationButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pointsCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
    marginTop: Spacing.lg,
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.lg,
    borderRadius: BorderRadius['3xl'],
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  pointsLabel: {
    fontSize: FontSizes.xs,
    fontWeight: FontWeights.semibold,
    color: 'rgba(255, 255, 255, 0.8)',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  pointsValue: {
    fontSize: FontSizes['4xl'],
    fontWeight: FontWeights.extrabold,
    color: Colors.neutral[0],
    marginTop: Spacing.sm,
  },
  pointsIcon: {
    backgroundColor: '#fbbf24',
    width: 52,
    height: 52,
    borderRadius: BorderRadius['3xl'],
    alignItems: 'center',
    justifyContent: 'center',
    transform: [{ rotate: '8deg' }],
  },
  statsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: Spacing.lg,
    paddingHorizontal: Spacing.sm,
  },
  statDivider: {
    width: 1,
    backgroundColor: 'rgba(255,255,255,0.2)',
    marginVertical: 4,
  },
  contentSection: {
    paddingHorizontal: Spacing.lg,
    marginTop: -Spacing['2xl'],
  },
  errorBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#fefce8',
    borderWidth: 1,
    borderColor: '#fde68a',
    borderRadius: BorderRadius.xl,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    marginBottom: Spacing.md,
  },
  errorText: {
    flex: 1,
    color: '#78350f',
    fontSize: FontSizes.xs,
    fontWeight: FontWeights.semibold,
  },
  actionCardsRow: {
    flexDirection: 'row',
    gap: Spacing.md,
  },
  sectionTitle: {
    fontSize: FontSizes.xl,
    fontWeight: FontWeights.extrabold,
    color: Colors.neutral[800],
    marginTop: Spacing.lg,
    marginBottom: Spacing.md,
  },
  challengeCard: {
    backgroundColor: Colors.neutral[0],
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.lg,
    borderRadius: BorderRadius['3xl'],
    borderWidth: 1,
    borderColor: Colors.primary[100],
    ...cardShadow,
  },
  challengeHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: Spacing.md,
  },
  challengeInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  trophyIcon: {
    backgroundColor: '#fef3c7',
    width: 44,
    height: 44,
    borderRadius: BorderRadius.xl,
    alignItems: 'center',
    justifyContent: 'center',
  },
  challengeDetails: {
    marginLeft: Spacing.md,
    flex: 1,
  },
  challengeTitle: {
    fontSize: FontSizes.base,
    fontWeight: FontWeights.bold,
    color: Colors.neutral[900],
  },
  challengeSubtitle: {
    fontSize: FontSizes.xs,
    fontWeight: FontWeights.normal,
    color: Colors.neutral[400],
  },
  challengePoints: {
    fontSize: FontSizes.base,
    fontWeight: FontWeights.bold,
    color: Colors.primary[500],
  },
  progressBarContainer: {
    height: 8,
    backgroundColor: Colors.neutral[100],
    borderRadius: BorderRadius.full,
    marginTop: Spacing.md,
    overflow: 'hidden',
  },
  progressBar: {
    height: '100%',
    backgroundColor: '#22c55e',
    borderRadius: BorderRadius.full,
  },
  activityHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: Spacing.lg,
    marginBottom: Spacing.md,
  },
  seeAllLink: {
    fontSize: FontSizes.base,
    fontWeight: FontWeights.bold,
    color: Colors.primary[500],
  },
  emptyStateWrap: {
    alignItems: 'center',
    paddingVertical: Spacing.lg,
    gap: 8,
  },
  emptyState: {
    fontSize: FontSizes.base,
    fontWeight: FontWeights.normal,
    color: Colors.neutral[400],
    textAlign: 'center',
  },
  issueCard: {
    backgroundColor: Colors.neutral[0],
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.md,
    borderRadius: BorderRadius['3xl'],
    marginBottom: Spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Colors.neutral[100],
    ...cardShadow,
  },
  issueImage: {
    width: 72,
    height: 72,
    borderRadius: BorderRadius.xl,
    backgroundColor: Colors.neutral[100],
  },
  issueContent: {
    flex: 1,
    marginLeft: Spacing.md,
  },
  issueTitle: {
    fontSize: FontSizes.base,
    fontWeight: FontWeights.bold,
    color: Colors.neutral[900],
  },
  issueAddress: {
    fontSize: FontSizes.xs,
    fontWeight: FontWeights.normal,
    color: Colors.neutral[400],
    marginTop: 4,
  },
  issueMetaTags: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: Spacing.sm,
  },
  statusBadge: {
    paddingHorizontal: Spacing.md,
    paddingVertical: 4,
    borderRadius: BorderRadius.full,
  },
  statusText: {
    fontSize: 10,
    fontWeight: FontWeights.extrabold,
    textTransform: 'uppercase',
  },
  categoryTag: {
    fontSize: 10,
    fontWeight: FontWeights.bold,
    color: Colors.neutral[300],
    marginLeft: Spacing.md,
    textTransform: 'uppercase',
  },
  bottomSpacer: {
    height: 80,
  },
});
