import { Platform, StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f0fdf4' },
  topBar: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 52 : 44,
    left: 12,
    right: 12,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'white',
    borderRadius: 16,
    paddingVertical: 10,
    paddingHorizontal: 12,
    shadowColor: '#000',
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 6,
  },
  backBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  topBarCenter: { flex: 1 },
  topBarTitle: { fontSize: 11, fontWeight: '700', color: '#6b7280', textTransform: 'uppercase', letterSpacing: 0.5 },
  topBarSubtitle: { fontSize: 16, fontWeight: '800', color: '#111827', marginTop: 2 },
  topBarRight: { width: 44 },
  directionsCard: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'white',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    paddingBottom: 36,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 16,
    elevation: 8,
  },
  directionStep: { flexDirection: 'row', alignItems: 'flex-start', gap: 12 },
  stepIcon: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#dcfce7', alignItems: 'center', justifyContent: 'center' },
  stepContent: { flex: 1 },
  stepTitle: { fontSize: 10, fontWeight: '800', color: '#94a3b8', letterSpacing: 1, textTransform: 'uppercase', marginBottom: 2 },
  stepAddress: { fontSize: 14, fontWeight: '600', color: '#111827' },
  directionLine: { width: 2, height: 16, backgroundColor: '#e5e7eb', marginLeft: 19, marginVertical: 4 },
  directionStats: { flexDirection: 'row', justifyContent: 'space-around', marginVertical: 16, paddingVertical: 12, backgroundColor: '#f0fdf4', borderRadius: 16 },
  statBox: { alignItems: 'center', gap: 2 },
  statValue: { fontSize: 16, fontWeight: '900', color: '#16a34a' },
  statLabel: { fontSize: 11, fontWeight: '600', color: '#6b7280' },
  openMapsBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    backgroundColor: '#f0fdf4',
    padding: 14,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: '#16a34a',
    marginBottom: 10,
  },
  openMapsBtnText: { fontSize: 15, fontWeight: '800', color: '#16a34a' },
  endBtn: { backgroundColor: '#16a34a', padding: 16, borderRadius: 16, alignItems: 'center' },
  endBtnText: { color: 'white', fontSize: 16, fontWeight: '900' },
  webPlaceholder: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 24, gap: 16 },
  webTitle: { fontSize: 20, fontWeight: '900', color: '#111827', textAlign: 'center' },
  webDesc: { fontSize: 14, color: '#6b7280' },
  locationWarning: {
  flexDirection: 'row',
  alignItems: 'center',
  gap: 6,
  backgroundColor: '#fef9c3',
  paddingHorizontal: 10,
  paddingVertical: 6,
  borderRadius: 8,
  marginBottom: 10,
},
locationWarningText: { fontSize: 12, fontWeight: '600', color: '#92400e', flex: 1 },
});
