import { StyleSheet } from 'react-native';

export const ecoRoutesStyles = StyleSheet.create({
  container: { flex: 1 },
  webPlaceholder: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 24 },
  webTitle: { fontSize: 16, color: '#6b7280' },
  searchCard: {
    position: 'absolute',
    top: 0,
    left: 16,
    right: 16,
    backgroundColor: 'white',
    borderRadius: 16,
    padding: 14,
    shadowColor: '#000',
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 6,
  },
  searchRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 8 },
  searchLabel: { fontSize: 14, fontWeight: '700', color: '#111827', flex: 1 },
  searchInput: { flex: 1, fontSize: 16, color: '#111827', paddingVertical: 4 },
  searchSubmit: {
    position: 'absolute',
    right: 14,
    top: 14,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#16a34a',
    alignItems: 'center',
    justifyContent: 'center',
  },
  myLocationBtn: {
    position: 'absolute',
    right: 16,
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  bottomSheet: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'white',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingTop: 16,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 16,
    elevation: 8,
    maxHeight: 220,
  },
  sheetLoading: { alignItems: 'center', paddingVertical: 24, gap: 12 },
  sheetLoadingText: { fontSize: 14, color: '#6b7280', fontWeight: '600' },
  cardsScroll: { paddingHorizontal: 16, gap: 12, flexDirection: 'row', paddingBottom: 12 },
  routeCard: {
    width: 160,
    backgroundColor: '#f8fafc',
    borderRadius: 16,
    padding: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  routeCardIcon: { width: 44, height: 44, borderRadius: 12, alignItems: 'center', justifyContent: 'center', marginBottom: 8 },
  routeCardMode: { fontSize: 15, fontWeight: '800', color: '#111827' },
  routeCardDuration: { fontSize: 18, fontWeight: '900', color: '#16a34a', marginTop: 2 },
  routeCardDistance: { fontSize: 12, color: '#6b7280', marginTop: 2 },
  ecoBadge: { alignSelf: 'flex-start', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8, marginTop: 6 },
  ecoBadgeText: { fontSize: 11, fontWeight: '800' },
  co2Text: { fontSize: 11, color: '#6b7280', marginTop: 4 },
  ptsChip: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 4 },
  ptsChipText: { fontSize: 11, fontWeight: '800', color: '#b45309' },
  startJourneyBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#16a34a',
    marginHorizontal: 16,
    padding: 16,
    borderRadius: 16,
  },
  startJourneyBtnText: { color: 'white', fontSize: 16, fontWeight: '900' },
  sheetHint: { textAlign: 'center', color: '#94a3b8', fontSize: 14, paddingVertical: 24 },
  errorBanner: {
    position: 'absolute',
    left: 16,
    right: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#fef9c3',
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#fde047',
  },
  errorBannerText: { flex: 1, fontSize: 13, fontWeight: '600', color: '#92400e' },
});